# [START gae_quickstart_yaml]
runtime: nodejs10
vpc_access_connector:
  name: "projects/poke-love/locations/us-central1/connectors/poke-love-vpn-connector"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
# [END gae_quickstart_yaml]

